#!/bin/zsh
set -euf -o pipefail

##
# Launch tmux with a sesson and windows suitable for Sapper development.
#
# Syntax:
#
#     tmux-start-sapper [session-name]
#
# Example:
#
#     cd myapp
#     tmux-start-sapper
#
#
# ## What this does
#
# The script attaches to session-name.
#
#   * If the session doesn't exist, then this creates it.
#   * The _session-name_ defaults to the basename of the pwd.
#
# The script launches these windows with these commands:
#
#   * 1:ed (editor) = `$EDITOR`
#   * 2:qa (quality assurance) = `npm run cy:run`
#   * 3:ll (log list) = `tail -f log/$SAPPER_ENV.log`
#   * 4:cc (console) = `sapper console`
#   * 5:db (database) = `psql`
#   * 6:ws (webserver) = `npm run dev`
#   * 7:bg (background misc. work, such as command line tools)
#   * 8:cd (continuous deployment, such as integration and delivery)
#   * 9:op (operations monitoring, such as metrics and analytics) 
#
#
# ## Tracking
#
# Program: tmux-start-sapper
# Version: 1.1.0
# Created: 2019-11-04
# Updated: 2020-05-24
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

# Choose an editor, or none.
if [ -z ${EDITOR+_} ]; then
  EDITOR=""
fi

# The sapper environment default is "dev".
SAPPER_ENV=${SAPPER_ENV:-dev}

# The session name default is the current directory's basename.
session_name=${1-$(basename $(pwd))}

tmux-starter "$session_name" \
"ed" "$EDITOR" \
"qa" "npm run cy:run" \
"ll" "tail -f log/$SAPPER_ENV.log" \
"cc" "" \
"db" "psql" \
"ws" "npm run $SAPPER_ENV" \
"bg" ":" \
"cd" ":" \
"op" ":"
